spring:
  application:
    name: gateway
  config:
    import: "consul:"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      host: localhost #host: 192.168.178.100
      port: 8500
      discovery:
        register: false
        registerHealthCheck: false
server:
  port: ${PORT:8079}